### PR TITLE
Packages definition

### PR DESCRIPTION
**Pull request by marcoceppi**
Allow layers to define additional packages to install at time of bootstrap

### CODE REVIEW

**Comment by marcoceppi** [comment]
This depends on juju/charm-tools#85 it's also a bit more than what we may want in a base layer. I can separate out the commits and just include the one for removing .bootstrapped file on upgrade-charm which does not depend on this change and shouldn't be as controversial

**Comment by johnsca** [comment]
Thanks for this!  I've been wanting to get around to doing something along these lines for a bit.

I do think that it's reasonable for the base layer, but as a counterpoint, Stuart had [this](https://git.launchpad.net/~stub/charms/+source/postgresql/tree/reactive/apt.py?h=reactive) that he was suggesting could make a separate layer which uses states and unitdata to control the package install.  That does give more flexibility, and can thus handle things like config-driven PPAs, but this approach has a much easier UI for the common case of just needing a few specific packages installed.  Maybe the approaches complementary and not mutually exclusive (e.g., layer opts package lists are for charm deps, like the wheelhouse, and the apt layer is for payload deps)?  Regardless, I do think this PR should probably include some support for custom PPAs, though.

There is also some overlap between this PR and #17 but I like your implementation better and am for closing #17 in favor of this PR.

Also +1 to the `.bootstrapped` fix.

**Comment by marcoceppi** [comment]
@johnsca I've updated based on feedback. This still suffers from juju/charm-tools#85 however.

**Comment by johnsca** [comment]
:shipit:

**Pull request merged**
